services:

  database:
    image: postgres:latest
    container_name: servicos_auto_db
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: servicos_auto
      POSTGRES_PASSWORD: servicos_auto
      POSTGRES_DB: servicos_auto
      POSTGRES_MEM: 80M
    mem_limit: 128M
    mem_reservation: 96M
    cpus: 0.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U servicos_auto"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - grafana_sentinel


  servicos_auto:
    build:
      context: .
      dockerfile: Dockerfile   # <== CORRIGIDO
    container_name: Sentinel_API-02
    restart: always
    ports:
      - "8085:8085"
    environment:

      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/servicos_auto
      SPRING_DATASOURCE_USERNAME: servicos_auto
      SPRING_DATASOURCE_PASSWORD: servicos_auto

      # Cloudinary
      CLOUDINARY_URL: cloudinary://165568658442188:iHo1y5Ee0RxvqD9wDXzMn5KjP4k
      CLOUDINARY_CLOUD_NAME: Root

      # OpenTelemetry
      OTEL_EXPORTER_OTLP_ENDPOINT: http://sentinel-otel:4317   # <== CORRIGIDO
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc                        # <== ADICIONADO
      OTEL_SERVICE_NAME: Sentinel_API-02
      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp

      OTEL_INSTRUMENTATION_HTTP_SERVER_ENABLED: "true"
      OTEL_INSTRUMENTATION_JVM_METRICS_EXPERIMENTAL_ENABLED: "true"
      OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED: "true"
      OTEL_INSTRUMENTATION_RUNTIME_METRICS_ENABLED: "true"

    mem_limit: 1024M
    mem_reservation: 768M
    cpus: 0.5
    
    depends_on:
      database:
        condition: service_healthy

    networks:
      - grafana_sentinel


networks:
  grafana_sentinel:
    external: true
