# Estágio de build: usa uma imagem com Maven e Java 21 para compilar o projeto
FROM maven:3.9.9-amazoncorretto-21-al2023 as build

# Define o diretório de trabalho dentro do container
WORKDIR /build

# Copia todos os arquivos do projeto para o diretório /build no container
COPY . .

# Executa o comando Maven para compilar o projeto e gerar o arquivo JAR
RUN mvn clean package -DskipTests


# Estágio final: imagem leve com apenas Java 21
FROM amazoncorretto:21

# Diretório de trabalho
WORKDIR /app

# Copia o arquivo JAR gerado pelo Maven
COPY --from=build /build/target/*.jar /app/servicos_auto.jar

# Baixa o agente do OpenTelemetry
RUN curl -L -o /app/opentelemetry-javaagent.jar \
    https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar

# Expõe a porta da aplicação
EXPOSE 8085

# Comando para iniciar a aplicação com o agente OpenTelemetry
ENTRYPOINT ["java", "-javaagent:/app/opentelemetry-javaagent.jar", "-jar", "servicos_auto.jar"]
