# ======================
# CONFIGURAÇÕES DO BANCO
# ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/eventmasterdb
# Caso use Docker Compose, descomente a linha abaixo:
# spring.datasource.url=jdbc:postgresql://eventmaster-db:5432/eventmasterdb
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Porta interna da aplicação (Dockerfile expõe 8080)
server.port=8080

# ======================
# LOGS SQL (opcional)
# ======================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ======================
# ACTUATOR / MÉTRICAS
# ======================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
