services:
  eventmaster-db:
    image: postgres:15
    container_name: eventmaster-db
    restart: always
    environment:
      POSTGRES_DB: eventmasterdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
    ports:
      - "5437:5432"  # Porta externa 5437 mapeando interna 5432
    volumes:
      - pgdata_eventmaster:/var/lib/postgresql/data
    networks:
      - grafana_sentinel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventuser -d eventmasterdb"] # <- CORREÇÃO APLICADA AQUI
      interval: 10s
      timeout: 5s
      retries: 5

  eventmaster-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventmaster-api
    restart: always
    depends_on:
      eventmaster-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Conexão com o banco
      SPRING_DATASOURCE_URL: jdbc:postgresql://eventmaster-db:5432/eventmasterdb
      SPRING_DATASOURCE_USERNAME: eventuser
      SPRING_DATASOURCE_PASSWORD: eventpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

      # OpenTelemetry
      OTEL_EXPORTER_OTLP_ENDPOINT: http://sentinel-otel:4318
      OTEL_SERVICE_NAME: eventmaster-api
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp

      # Java agent
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"

    networks:
      - grafana_sentinel
    volumes:
      - ./opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar:ro

volumes:
  pgdata_eventmaster:

networks:
  grafana_sentinel:
    external: true