services:
  eventmaster-db:
    image: postgres:15
    container_name: eventmaster-db
    restart: always
    environment:
      POSTGRES_DB: eventmasterdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
    ports:
      - "5437:5432"
    volumes:
      - pgdata_eventmaster:/var/lib/postgresql/data
    networks:
      - sentinel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  eventmaster-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventmaster-api
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      eventmaster-db:
        condition: service_healthy
       
    environment:
      # --------------------
      # Database connection
      # --------------------
      SPRING_DATASOURCE_URL: jdbc:postgresql://eventmaster-db:5432/eventmasterdb
      SPRING_DATASOURCE_USERNAME: eventuser
      SPRING_DATASOURCE_PASSWORD: eventpass
      
      # --------------------
      # OpenTelemetry
      # --------------------
      # --- Adiciona o agente Java na inicialização ---
      JAVA_TOOL_OPTIONS: -javaagent:/app/opentelemetry-javaagent.jar

      # O endpoint correto para o OTLP/gRPC é 4317
      OTEL_EXPORTER_OTLP_ENDPOINT: http://sentinel-otel:4317
      OTEL_SERVICE_NAME: EventMaster_API

      # Exportadores (ativados)
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp

      # Instrumentações úteis
      OTEL_INSTRUMENTATION_HTTP_SERVER_ENABLED: "true"
      OTEL_INSTRUMENTATION_RUNTIME_METRICS_ENABLED: "true"
      OTEL_INSTRUMENTATION_JVM_METRICS_EXPERIMENTAL_ENABLED: "true"
      OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED: "true"
    volumes:
      # --- Monta o agente para dentro do contêiner ---
      # !!! IMPORTANTE: O agente deve estar neste caminho no seu PC.
      - C:/Otel/opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
    networks:
      - sentinel

volumes:
  pgdata_eventmaster:

networks:
  sentinel:
    external: true