version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pokemon_logs_db
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pokemon_logs

    ports:
      - "5434:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - grafana_sentinel

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pokemon_logs"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s


  api:
    container_name: pokemon-api
    build:
      context: .

    restart: always

    ports:
      - "3005:3000"
      - "9464:9464"   # <- Prometheus metrics expostas NO HOST

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    environment:
      NODE_ENV: production

      # ================================================
      # OPEN TELEMETRY — TRACING E LOGS
      # ================================================
      OTEL_SERVICE_NAME: pokemon-api

      # Protocolo obrigatorio no Node
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

      # Endpoint principal
      OTEL_EXPORTER_OTLP_ENDPOINT: http://sentinel-otel:4318

      # Endpoints específicos
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://sentinel-otel:4318/v1/traces
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://sentinel-otel:4318/v1/logs

      # Node NÃO suporta métricas OTLP
      OTEL_METRICS_EXPORTER: none

      # Ativar exportadores
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp

      # Correlação logs <-> traces
      OTEL_LOGS_INCLUDE_TRACE_CONTEXT: "true"

      # Report de erros mais verboso
      OTEL_LOG_LEVEL: debug

    networks:
      - grafana_sentinel

    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


volumes:
  pgdata:

networks:
  grafana_sentinel:
    external: true
